### ISSUE TITLE
Cannot perform Client Credential flow without using `meteor-accounts-spotify`

### ISSUE THREAD

**Issue by dstotijn** [xinranxiao/meteor-spotify-web-api#2]
Hi,

I've been trying to connect to the Spotify Web API using the "Client Credential flow", e.g. using the application's clientID and clientSecret to authorize server side, _without_ user account authorization.

When I call the `SpotifyWebApi` function provided by this wrapper (supplying a `clientId` and `clientSecret`) I do not have an access token yet to pass to the constructor, and the following error is thrown:

```
Error: No accessToken found. Please provide an accessToken or login with xinranxiao:accouns-spotify at setAccessTokens (packages/xinranxiao_spotify-web-api/packages/xinranxiao_spotify-web-api.js:126:1)
```

My question: How do I create a new `SpotifyWebApi` object in this wrapper without an access token?

**Comment by remcorakers** [comment]
I have the same question. Step 2 in the readme describes "Get an oauth access_token, either through xinranxiao:accounts-spotify, or directly through this API (refer here. ) for how).". But I can't find a way to get the access token via this API. Any help is appreciated!

**Comment by felicedeNigris** [comment]
I'm having the same issue. If I type `Meteor.loginwithSpotify()`in my chrome browser console I get `undefined` meaning  I am logged out because of no access token .

**Comment by xinranxiao** [comment]
Woops totally didn't read this until now. So this is happening because of this if statement I have when instantiating the SpotifyWebApi class:

```
} else {
  // No token specified
  throw new Error("No accessToken found. Please provide an accessToken or login with xinranxiao:accouns-spotify");
}
```

I am going to delete that part of the code, which will allow you do create a `SpotifyWebApi` object without having to have an access token.

**Comment by xinranxiao** [comment]
This should be good now: https://github.com/xinranxiao/meteor-spotify-web-api/commit/a0b6d9d2dd5c1b304032175d70d5b3e77ee3431f
