### ISSUE TITLE
Will there be a support for method getMySavedAlbums?

### ISSUE THREAD

**Issue by matthlavacka** [xinranxiao/meteor-spotify-web-api#4]
When calling it I'm getting the following error message: 

```
Exception while invoking method 'getMySavedAlbums' TypeError: Object [object Object] has no method 'getMySavedAlbums'
```

**Comment by xinranxiao** [comment]
I'll do an update in a few hours and it should be up by end of day today. Thanks for mentioning this.

**Comment by xinranxiao** [comment]
It is done. Please update to 1.0.2 and enjoy!
