### ISSUE TITLE
I experience really strange behavior trying to login on iOS in Chrome, works in Safari

### ISSUE THREAD

**Issue by matthlavacka** [xinranxiao/meteor-spotify-web-api#5]
I tried to login from multiple iOS devices on your example app and also the one I implemented this accounts in and it just opens and closes the new window right after without login in.  Not sure if that's Spotify issue

**Comment by xinranxiao** [comment]
Hmm, have you tried google oauth (using the meteor package) on iOS chrome devices? This is implemented very similarly.. let me know if that works and we can debug further.
