### ISSUE TITLE
401 (Unauthorized)

### ISSUE THREAD

**Issue by felicedeNigris** [xinranxiao/meteor-spotify-web-api#6]
I am able to login with `xinranxiao/meteor-accounts-spotify` successfully. And with `meteor-spotify-web-api` I am able to call the NodeJS Spotify methods to access data. 

However I am unable to point to direct hrefs or uri of playlist tracks without getting a 401 error.
`GET https://api.spotify.com/v1/users/felideni/playlists/48J5k0lJh1M0pLZImt6c6l 401 (Unauthorized)`

In my console I see the 401 error and also `S…n.ConfigError {message: "Login service configuration not yet loaded"}`

I am puzzled because I am able to login and access data, but to point at it and access it I get an error. 

I am refreshing my token also ? 

```
  // Get a user's playlists
  getUserPlaylists: function() {
    //Spotify call
    let spotifyApi = new SpotifyWebApi()
    //response object
    let userplaylists = spotifyApi.getUserPlaylists(Meteor.user().profile.id,function(err,data){
      if(err){
        console.log("Retrieval error ", err)
      }
      else{
        console.log("Success, your playlist ", data.body)
      }
    })
    //Need to refresh token
    if(checkTokenRefreshed(userplaylists, spotifyApi)){
      userplaylists = spotifyApi.getUserPlaylists(Meteor.user().profile.id,function(err,data){
        if(err){
          console.log("Retrieval error ", err)
        }
        else{
          console.log("Success, your playlist ", data.body)
        }
      })//end response
    }//end checkTokenRefreshed

    return userplaylists

  }//end getUserPlaylists
```

[Here's my repo](https://github.com/felicedeNigris/MixtapeForum)

**Comment by felicedeNigris** [comment]
Hey @xinranxiao , You can close this. I figured out that I was getting a `401` error when I plugged the wrong uri into the `<iframe></iframe>` player. I hadn't read much of the documentation on it prior, but now I got it to work.

**Comment by xinranxiao** [comment]
Good job figuring it out! Sorry I didn't have the time to help you with this.

**Comment by felicedeNigris** [comment]
I'm glad I did also. No worries I understand :smile_cat:
