### ISSUE TITLE
Stuck Extracting on Meteor 1.4.1.1

### ISSUE THREAD

**Issue by mcgovey** [xinranxiao/meteor-spotify-web-api#8]
When I try to add the package 'meteor add xinranxiao:spotify-web-api' the install never gets past 'Extracting xinranxiao:spotify-web-api...'.  

I've tried solutions suggested elsewhere with making sure all other packages in the project are up-to-date and that my unzip tool is working properly (I'm able to install other packages).  I'm on Windows 10, Meteor 1.4.1.1

**Comment by xinranxiao** [comment]
I'll check it out and see if I can reproduce it -- is there anything special you are doing?

**Comment by mcgovey** [comment]
Nope, just trying to install on a barebones project. Thanks for taking a
look!!

**Comment by xinranxiao** [comment]
Looks like this thread explains the culprit: https://github.com/meteor/meteor/issues/7688

Check it out and see if it helps

**Comment by xinranxiao** [comment]
This may also help: https://forums.meteor.com/t/solution-to-meteor-hanging-extracting-package-on-windows/28873

**Comment by mcgovey** [comment]
I tried those but no luck getting it to work.  I was able to get it working when I installed the package locally.  Not ideal but it'll have to do for now.  Thank you so much for your help!!  Looking forward to using this package
